# Generated by Django 5.2.7 on 2025-10-25 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('GEN', 'General'), ('ALM', 'Alarma'), ('POM', 'Pomodoro'), ('FRQ', 'Solicitud de amistad'), ('STM', 'Logro de estudio'), ('ACH', 'Logro desbloqueado')], default='GEN', max_length=3, verbose_name='tipo')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('priority', models.CharField(choices=[('L', 'Baja'), ('M', 'Media'), ('H', 'Alta')], default='M', max_length=1, verbose_name='prioridad')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='leída')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='descartada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='leída el')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='tipo de contenido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['is_read', 'is_dismissed'], name='notificatio_is_read_578b5d_idx')],
            },
        ),
    ]
