# Generated by Django 5.2.7 on 2025-10-24 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'asignatura',
                'verbose_name_plural': 'asignaturas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Imagen, esquema o captura (opcional).', null=True, upload_to='posts/images/', verbose_name='imagen')),
                ('caption', models.TextField(blank=True, help_text='Breve descripción o contexto del resumen.', max_length=1000, verbose_name='caption')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('is_public', models.BooleanField(default=True, help_text='Si es False, el post sólo será visible para el autor o seguidores si la lógica lo permite.', verbose_name='público')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='likes')),
                ('saved_by', models.ManyToManyField(blank=True, related_name='saved_posts', to=settings.AUTH_USER_MODEL, verbose_name='guardado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('subjects', models.ManyToManyField(blank=True, help_text='Etiquetas de las asignaturas relacionadas con el post.', related_name='posts', to='posts.subject', verbose_name='asignaturas')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='posts_post_created_dadbfe_idx')],
            },
        ),
    ]
