# Generated by Django 5.2.7 on 2025-10-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, help_text='Breve descripción del resumen.', max_length=1000, verbose_name='caption'),
        ),
    ]
