# Generated by Django 5.2.7 on 2025-10-24 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_options_userprofile_following_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name': 'solicitud de amistad', 'verbose_name_plural': 'solicitudes de amistad'},
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='profiles.userprofile', verbose_name='usuario que envía'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='respondida'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='profiles.userprofile', verbose_name='usuario receptor'),
        ),
    ]
