# Generated by Django 5.2.7 on 2025-10-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_friendrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Escribe una breve descripción.', max_length=500, verbose_name='bio'),
        ),
    ]
