# Generated by Django 5.2.7 on 2025-10-25 15:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo para la alarma', max_length=100, verbose_name='nombre')),
                ('time', models.TimeField(verbose_name='hora')),
                ('days', models.JSONField(default=list, help_text='Lista de días de la semana (0-6, 0=Lunes)', verbose_name='días')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'alarma',
                'verbose_name_plural': 'alarmas',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='PomodoroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_duration', models.PositiveIntegerField(default=25, help_text='Duración del período de trabajo en minutos', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='duración trabajo')),
                ('break_duration', models.PositiveIntegerField(default=5, help_text='Duración del período de descanso en minutos', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='duración descanso')),
                ('long_break_duration', models.PositiveIntegerField(default=15, help_text='Duración del descanso largo en minutos', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='duración descanso largo')),
                ('sessions_until_long_break', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='sesiones hasta descanso largo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_settings', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'configuración pomodoro',
                'verbose_name_plural': 'configuraciones pomodoro',
            },
        ),
        migrations.CreateModel(
            name='PostIt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='contenido')),
                ('color', models.CharField(default='#ffeb3b', help_text='Color en formato hex (#ffeb3b)', max_length=7, verbose_name='color')),
                ('position_x', models.IntegerField(default=0, verbose_name='posición X')),
                ('position_y', models.IntegerField(default=0, verbose_name='posición Y')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postits', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'post-it',
                'verbose_name_plural': 'post-its',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('duration', models.DurationField(blank=True, help_text='Duración total de la sesión', null=True, verbose_name='duración')),
                ('notes', models.TextField(blank=True, help_text='Notas o comentarios sobre la sesión', verbose_name='notas')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='posts.subject', verbose_name='asignatura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'sesión de estudio',
                'verbose_name_plural': 'sesiones de estudio',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', 'subject', 'start_time'], name='study_study_user_id_6f426c_idx')],
            },
        ),
    ]
